### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by anhphongbkdn** [yigolden/http-to-socks5-proxy#1]
Can you add an example? I want to convert from http to socks5. I'm ran command: HttpToSocks5Proxy.exe --inbound http://117.0.196.141:13938 --outbound socks5: //192.168.1.2: 1618
But it doesn't seem to work. Please help. Thank you

**Comment by MM-YJN** [comment]
Are you trying to setup a SOCKS5 proxy server that forwards requests to your existing HTTP proxy server?

In this case, this project does not suit your need because it works the other way around. (It creates a HTTP proxy server that forwards requests to an SOCKS5 server.)

**Comment by anhphongbkdn** [comment]
Ok. Thank you for reply!
